# CREDENTIALS
GOOGLE_VISION_KEY_PATH = "services/databaseManagement/serviceAccountCredentials.json"


# DRIVE
GOOGLE_DRIVE_SCOPES = []
GOOGLE_DRIVE_SERVICE_NAME = "drive"
GOOGLE_DRIVE_API_VERSION = "v3"

# DOCS
GOOGLE_DOCS_SERVICE_NAME = "docs"
GOOGLE_DOCS_API_VERSION = "v1"
THIRD_PARTY_LEAD_EMAIL_ID = ""

# SHEETS
GOOGLE_SHEETS_SERVICE_NAME = "sheets"
GOOGLE_SHEETS_API_VERSION = "v1"
GOOGLE_SHEETS_SCOPES = ['https://www.googleapis.com/auth/spreadsheets']